FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD telco-micro-java-arch-restblank.jar /opt/telco-micro-java-arch-restblank/
EXPOSE 8080
WORKDIR /opt/telco-micro-java-arch-restblank/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "telco-micro-java-arch-restblank.jar"]
